CREATE DATABASE IF NOT EXISTS banque;
CREATE TABLE IF NOT EXISTS CLIENTS (
    CODE_CLIENT BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOM_CLIENT VARCHAR(255),
    PRENOM_CLIENT VARCHAR(255),
    ADR_CLIENT VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS EMPLOYES (
    CODE_EMPLOYE BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOM_EMPLOYE VARCHAR(255),
    CODE_SUP BIGINT,
    FOREIGN KEY (CODE_SUP) REFERENCES EMPLOYES(CODE_EMPLOYE)
);
CREATE TABLE IF NOT EXISTS GROUPES (
    CODE_GROUPE BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOM_GROUPE VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS EMPLOYE_GROUPE (
    CODE_EMPLOYE BIGINT,
    CODE_GROUPE BIGINT,
    PRIMARY KEY (CODE_EMPLOYE, CODE_GROUPE),
    FOREIGN KEY (CODE_EMPLOYE) REFERENCES EMPLOYES(CODE_EMPLOYE),
    FOREIGN KEY (CODE_GROUPE) REFERENCES GROUPES(CODE_GROUPE)
);
CREATE TABLE IF NOT EXISTS COMPTES (
    CODE_COMPTE VARCHAR(255) PRIMARY KEY,
    DATE_CREATION DATE,
    SOLDE DOUBLE,
    CODE_CLIENT BIGINT,
    CODE_EMPLOYE BIGINT,
    TYPE_COMPTE VARCHAR(4),
    DECOUVERT DOUBLE,
    TAUX_INTERET DOUBLE,
    FOREIGN KEY (CODE_CLIENT) REFERENCES CLIENTS(CODE_CLIENT),
    FOREIGN KEY (CODE_EMPLOYE) REFERENCES EMPLOYES(CODE_EMPLOYE)
);
CREATE TABLE IF NOT EXISTS OPERATIONS (
    NUMERO_OPERATION BIGINT PRIMARY KEY AUTO_INCREMENT,
    DATE_OPERATION DATE,
    MONTANT DOUBLE,
    CODE_COMPTE VARCHAR(255),
    CODE_EMPLOYE BIGINT,
    TYPE_OP VARCHAR(4),
    FOREIGN KEY (CODE_COMPTE) REFERENCES COMPTES(CODE_COMPTE),
    FOREIGN KEY (CODE_EMPLOYE) REFERENCES EMPLOYES(CODE_EMPLOYE)
);
